### ISSUE TITLE
[Bug]: Toggle buttons design issue

### ISSUE THREAD

**Issue by alsahlawi** [andreia/filament-nord-theme#5]
### What happened?

when using the theme, toggle buttons shows reversed 

![image](https://github.com/user-attachments/assets/82636839-d1c9-4d74-b8f8-2ee56035bab8)

P.S. Cool theme, thank you.

### How to reproduce the bug

     ToggleButtons::make('status')
                                ->label('Is active?')
                                ->default(true)
                                ->inline()
                                ->grouped()
                                ->required()
                                ->boolean()
                                ->columnSpan(4),

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by andreia** [comment]
@alsahlawi Thank you for reporting! :)
Added a fix on https://github.com/andreia/filament-nord-theme/pull/6
Please let me know if it´s working for you now

**Comment by alsahlawi** [comment]
Worked like a charm!
![image](https://github.com/user-attachments/assets/c47b137e-8b9e-400b-83ad-63ae094391bc)
